export { default as freshRegistrationReducer } from "./freshRegistrationSlice";
export { fetchDashboardData, fetchApplicationPreview, fetchBoardOptions, fetchHospitalOptions, fetchApplicationListData, fetchFeePaymentListData, fetchCertificateListData, fetchSmartCardData } from "./freshRegistrationSlice";
export { submitRenewalApplication, fetchApplicationTypesData, setRenewalPeriod, setEmploymentDetails, setApplicationUuid, resetOtherApplicationState } from "./otherApplicationSlice";
export {
  updatePersonal,
  updateEducation,
  setAdditionalQualifications,
  updateCommunicationAddress,
  setCommunicationAgreed,
  updateDocument,
  updateEducationDocument,
  setEducationDocuments,
  setDocuments,
  resetPersonalForm,
  resetDocuments,
  resetEducationDocuments,
  resetEducationSection,
  resetCommunicationSection,
  resetAllRegistration,
  setCurrentStep,
  nextStep,
  previousStep,
  setLoading,
  setError,
  setApplicationId,
  patchDashboardData,
} from "./freshRegistrationSlice";

export {
  selectPersonal,
  selectEducation,
  selectAdditionalQualifications,
  selectCommunication,
  selectEducationDocuments,
  selectDocuments,
  selectFullRegistration,
  selectCurrentStep,
  selectDashboardData,
  selectPreviewData,
  selectPreviewLoading,
  selectFreshRegistrationLoading,
  selectBoardOptions,
  selectBoardsLoading,
  selectHospitalOptions,
  selectHospitalsLoading,
  selectApplicationList,
  selectApplicationListLoading,
  selectFeePaymentList,
  selectFeePaymentListLoading,
  selectCertificateList,
  selectCertificateListLoading,
  selectSmartCardData,
  selectSmartCardLoading,
} from "../selectors/freshRegistrationSelectors";

export {
  selectOtherApplicationSubmitting,
  selectOtherApplicationSubmitError,
  selectOtherApplicationUuid,
  selectRenewalPeriod,
  selectApplicationTypes,
  selectApplicationTypesLoading,
  selectApplicationTypeByName,
  selectEmploymentDetails,
} from "../selectors/otherApplicationSelectors";
