export {
  selectPersonal,
  selectPersonalAadhaar,
  selectPersonalMobile,
  selectEducation,
  selectAdditionalQualifications,
  selectCommunication,
  selectPermanentAddress,
  selectCorrespondenceAddress,
  selectProfessionalAddress,
  selectCommunicationAgreed,
  selectEducationDocuments,
  selectDocuments,
  selectDocumentById,
  selectDocumentsWithStatus,
  selectApplicationId,
  selectFullRegistration,
  selectCurrentStep,
  selectFreshRegistrationLoading,
  selectFreshRegistrationError,
  selectIsFormComplete,
  selectDocumentUploadProgress,
} from "./freshRegistrationSelectors";
